### ISSUE TITLE
Confusion of which repo is most relevant this or AWS quickstart

### ISSUE THREAD

**Issue by vladibb** [tableau/server-install-script-samples#11]
https://github.com/aws-quickstart/quickstart-tableau-server/blob/master/templates/tableau-cluster.template

Seems to be updated much more often than this repo.
Is there any reason to have double repo googlable on the internet?

**Comment by kittychou** [comment]
Thanks for your feedback.  I have removed the outdated CloudFormation templates and replaced with a reference to the official AWS Quick Starts.
