### ISSUE TITLE
YAML please - no more CF in JSON

### ISSUE THREAD

**Issue by vladibb** [tableau/server-install-script-samples#12]
Please please please, use new awesome yaml format for your Cloudformation templates.
It's so much easier to track our main repo changes + do variable substitution.

It's very easy to convert existing JSON files into YAML - using **cfn-flip** python tool

```
public-sample-single-server.cfn
public-sample-ssl-cluster.cfn
public-sample-ssl-single-server.cfn
```

**Comment by kittychou** [comment]
Thanks for your feedback.  We will take this under consideration in future versions that we release.
