### ISSUE TITLE
ScriptedInstaller.py is not support CLUSTER construction using 2 Keys

### ISSUE THREAD

**Issue by vladibb** [tableau/server-install-script-samples#13]
Tableau Sales gives you two keys when using Tableau Cluster as:
* Primary + Worker
* Primary + Worker1 + Worker2

So whole setup fails, how to fix?
* Request new single cluster key 
or 
* adjust ScriptedInstaller.py

**Comment by kittychou** [comment]
You can easily modify the ScriptedInstaller.py script to accomodate this scenario, but duplicating the command for "tabadmin activate" with the second key.  This project is meant to be a reference implementation and we encourage you to customize for your own specific needs as necessary.  Let us know if there is anything else we can help with!
