### ISSUE TITLE
Option to install SSL

### ISSUE THREAD

**Issue by tekniboy1506** [tableau/server-install-script-samples#16]
Hi,
Could this script enable the Tableau Server with HTTPS and with pre-created SSL key and cert? I can't find any option to input the Key and Cert as in the Installation Wizard.
Thank You.

**Comment by kittychou** [comment]
Hi,  We have some documentation [here](https://onlinehelp.tableau.com/current/server/en-us/server_install_configopts.htm) that describes how you can customization your Tableau Server by providing a customer configuration file to the script.  This includes a description of the settings for specifying the location of the key/cert files.  You will also need to separately make sure that you copy those files to the location as specified in the configuration.
