### ISSUE TITLE
broken link "Automated Installation of Tableau Server" on linux doc

### ISSUE THREAD

**Issue by obazoud** [tableau/server-install-script-samples#22]
The link "Automated Installation of Tableau Server " (http://onlinehelp.tsi.lan/v10.5/server-linux/en-us/automated_install_linux.htm) is broken

https://github.com/tableau/server-install-script-samples/blob/master/linux/automated-installer/README.md

**Comment by kittychou** [comment]
The link appears to be working for me.  Could you please try again?
