### ISSUE TITLE
Windows Installation Failure: opens the Installer UI

### ISSUE THREAD

**Issue by skylerto** [tableau/server-install-script-samples#34]
Despite running with the `/VERYSILENT` option it looks like python opens the installer. When opened the installer prompts to accept the license (as if all options are ignored). 

I'm running on Windows Server 2016.

I'm running with the following options: 

`python install.py install --installerLog C:\Temp\tabinstall.txt --installDir C:\TableauServer --secretsFile secrets.json --registrationFile registration.json --trialLicense .\TableauDesktop-64bit-10-5-2.exe`

I can see all the _appropriate_ flags are being set. 

`Running: .\TableauDesktop-64bit-10-5-2.exe['/VERYSILENT', '/SUPPRESSMSGBOXES', '/ACCEPTEULA', '/DIR=C:\\TableauServer', '/LOG=C:\\Temp\\tabinstall.txt']`

Is there only supported versions?

**Comment by jcase** [comment]
The installer you're using is for the Tableau Desktop product. This script is used to install the server.

**Comment by skylerto** [comment]
@jcase thanks for getting back to me!

**Comment by skylerto** [comment]
@jcase do you know of any way to find a trial version of the server edition. I can’t seem to find any documentation or download on this.

**Comment by skylerto** [comment]
For future ref: https://www.tableau.com/products/server/download
