### ISSUE TITLE
Receiving Error Message - Does not update installed package. Error: Nothing to do. 

### ISSUE THREAD

**Issue by contrerasjdj** [tableau/server-install-script-samples#48]
I ran the automated installer once, and it worked. Now, I am trying to to some testing using some of the the other parameters (such as choosing a user) and when re-run the installer, I receive the following message:

/home/Folder/tableau-server-2018-1-2.x86_64.rpm: does not update installed package.
Error: Nothing to do

What can I do to resolve this issue? I did notice that when I ran the installer using a different version, it ran once but subsequently ran into the same issue.

**Comment by contrerasjdj** [comment]
Must remove all packages by running an 'sudo rpm -e --noscripts --nodeps tableau-server.xxx.xxx.rpm

**Comment by wxl3322335** [comment]
did you resolved this problem？
