### ISSUE TITLE
Linux CenTos: no such file or directory when running tsm intialize.

### ISSUE THREAD

**Issue by joracab** [tableau/server-install-script-samples#49]
![image](https://user-images.githubusercontent.com/1183779/42714563-46cb61c6-86b9-11e8-9510-e4c3cec83ee6.png)
 Hey guys, some with the same issue?

**Comment by kgeis** [comment]
@joracab, the screen shot is a little fuzzy. Can you post the output as text?

**Comment by samklr** [comment]
I have a similar issue : 
<img width="1424" alt="screen shot 2019-01-23 at 5 08 32 pm" src="https://user-images.githubusercontent.com/1344035/51619925-9f6ba000-1f31-11e9-80a7-97292768fe40.png">
I guess it's expect the package to be unarchived into a different repo.
