### ISSUE TITLE
installation fails on Ubuntu 16.04 due to unrecognized option

### ISSUE THREAD

**Issue by bzip2** [tableau/server-install-script-samples#61]
I'm running the automated installer on Ubuntu 16.04 on Google Cloud. I encounter a bug after registration completes:

> > Registration complete.
> > ...
> > Setting initial configuration...
> > ...
> > Applying pending changes...
> > + run_tsm pending-changes apply --restart
> > + tabadminArgs='pending-changes apply --restart'
> > + local 'escaped_tsm_admin_pass=[redacted]'
> > ++ hostname
> > + su -c '/path/to/tsm pending-changes apply --restart -u "tsmadmin" -s https://[ip.address.here]:8850' tsmadmin
> > Unrecognized option: --restart
> 

The problematic line in automated-installer is `run_tsm pending-changes apply --restart`. If I change `--restart` to `--ignore-prompt`, I'm able to continue the installation.

**Comment by Neustradamus** [comment]
@bzip2: I need to contact you (no link with this issue), what is your email or other possibility to contact you? Thanks in advance.

**Comment by cowens5** [comment]
This has been fixed in the latest version of the automated-installer script
