### ISSUE TITLE
"The parameter groupName cannot be used with the parameter subnet"

### ISSUE THREAD

**Issue by rkmasiello** [tableau/server-install-script-samples#8]
I had an issue with using the "SecurityGroups" property during the AWS::EC2::Instance event. I ended up using "SecurityGroupIds" instead which corrected the error.

**Comment by kittychou** [comment]
Thanks for your feedback.  We are deprecated this version of the CloudFormation templates.  Please refer to the AWS Quick Start for Tableau Server which can be found here: https://aws.amazon.com/quickstart/architecture/tableau-server/
